### ISSUE TITLE
[BUG] Aux Leveling doesn't disable mesh leveling

### ISSUE THREAD

**Issue by eblieb** [smith3d/Marlin#21]
https://github.com/smith3d/Marlin/blob/bugfix-2.0.x-Smith3D/Marlin/src/lcd/dwin/e3v2/dwin.cpp 

After line 2674 the following needs to be added
gcode.process_subcommands_now_P("M420 S0");

This is to disable mesh leveling (otherwise the Aux leveling will still use mesh data) since RESTORE_LEVELING_AFTER_G28 is on

**Comment by smith3d** [comment]
bug has been fixed in the latest alpha version
