### ISSUE TITLE
Changing Z-Offset is not moving the Z-Axis

### ISSUE THREAD

**Issue by tfaz099** [smith3d/Marlin#26]
### Bug Description

After performing a complete manual leveling, then a mesh level with the "level" menu item, storing and committing changes to eeprom, running the z-offset tool, and locking in the z-offset.

Reboot to start clean and confirm Z value is correct. the nozzle grinds into the bed.
Re Home
Move Z to 0
select Z Offset and start turning dial.... Z Does not move.  
Try clicking to "set z" ... Z still does not move

Re-Run z offset tool... z offset moves fine when turning dial.

Need z to move without clicking to commit when print is in progress.

### My Configurations

Using the existing Smith Binary for 4.2.2 BL Touch (Slow)

**Comment by smith3d** [comment]
usually it meant incorrect wiring. check ur bltouch wiring sequence, and reseat your bltouch wiring.

**Comment by tfaz099** [comment]
I think the resulting code / option change is : 
//#define AUTO_BED_LEVELING_BILINEAR  //comment out
#define AUTO_BED_LEVELING_UBL //uncomment supposedly this allows for active Z-Axis move live without having to re-home.  I will test soon.

***Update - this setting was not the one that activated the active movement for the Z, and using it turns off the level menu on the unit.

**Comment by tfaz099** [comment]
The "always use babysteps" was commented out, works fine now.
